### ISSUE TITLE
rr:languageColumn should validate lang; use rr:language as fallback

### ISSUE THREAD

**Issue by VladimirAlexiev** [antidot/db2triples#11]
[extractValueFromTermMap](https://github.com/antidot/db2triples/blob/7a240986b5bd79f0ebbaeadb4350f826df7a27b9/src/main/java/net/antidot/semantic/rdf/rdb2rdf/r2rml/core/R2RMLEngine.java#L570) gets a lang tag from getLanguageValue, which uses `rr:languageColumn`. But if there is no such value for the current row, it should use rr:language as fallback.

[generateLiteralTermType](https://github.com/antidot/db2triples/blob/7a240986b5bd79f0ebbaeadb4350f826df7a27b9/src/main/java/net/antidot/semantic/rdf/rdb2rdf/r2rml/core/R2RMLEngine.java#L798) gets a lang tag from getLanguageTag, which uses `rr:language`. It should be combined with the above.

The latter checks isValidLanguageTag, therefore the former should do the same. The check is done in generateLiteralTermType, but I think it's better to put both checks in the getters (getLanguageTag and getLanguageValue respectively).

**Comment by gesteban** [comment]
In [generateLiteralTermType](https://github.com/antidot/db2triples/blob/7a240986b5bd79f0ebbaeadb4350f826df7a27b9/src/main/java/net/antidot/semantic/rdf/rdb2rdf/r2rml/core/R2RMLEngine.java#L790), when the argument languageValue has a non-null value, means that it was extracted from the languageColumn property. Its validity is checked in the first line of the method.


Anyway, checking this issue I've found one error related with null values when using rr:languageColumn. In [generateRDFTriplesFromPredicateObjectMap](https://github.com/antidot/db2triples/blob/7a240986b5bd79f0ebbaeadb4350f826df7a27b9/src/main/java/net/antidot/semantic/rdf/rdb2rdf/r2rml/core/R2RMLEngine.java#L611) the code checks for null values in the data extracted from the database, and skips the generation of the map if a null value if found. Now the value found in the database could be null (cause we have rr:language as fallback), this piece of code has to be addressed. I'll take a look at this, but before continuing I have a few questions about the desired behavior:
- When should we use rr:language as fallback? only when the value of the value of its column is null, or with any column value that is not a valid language.
- Given a mapping using rr:languageColumn but no rr:language. What should we do when the value of the column is null or not valid, throw an error? warning? simply don't put a language? is a null value the same as a not valid value?

**Comment by VladimirAlexiev** [comment]
@gesteban I think you should throw exception on invalid values (but Antidot should fix #12).

> skips the generation of the map

Yes, you shouldn't do this: the map generation shouldn't even check what's in the database.

Use the fallback only when the languageValue is null.
If there is no fallback, don't put a language.

Cheers!

**Comment by gesteban** [comment]
resolved in https://github.com/gesteban/db2triples, merge request pendant

- fallback is only used when languageValue is null
- when languageValue is not a valid language tag, now it throws an exception

**Comment by psass-antidot** [comment]
Fixed in #14
