### ISSUE TITLE
use rrx: namespace not rr: namespace for languageColumn

### ISSUE THREAD

**Issue by VladimirAlexiev** [antidot/db2triples#13]
I think it's better to use a custom namespace for the `languageColumn` extension:
`      @prefix rrx:  <http://purl.org/r2rml-ext/>.`
rather than the standard namespace:
`      @prefix rr:   <http://www.w3.org/ns/r2rml#>.`
- I believe we cannot add to the standard namespace just like this
- the Perl implementation uses the extension namespace as a precedent
- it's beneficial if all implementations designate the extension using the same namespace, to facilitate script compatibility.

@gesteban wrote "I agree. I only maintained the rr prefix because it was easier to develop that way (to use the rrx prefix db2triples needs more classes and changes in some algorithms, but to add a new property to the rr prefix was way faster). I will try to fix it next week and create a new MR."

**Comment by gesteban** [comment]
resolved in https://github.com/gesteban/db2triples, merge request pendant
