### ISSUE TITLE
Upgrade to RDF4J

### ISSUE THREAD

**Issue by aschwarte10** [antidot/db2triples#15]
The project is currently built against a pretty old version of Sesame.

In the meantime RDF4J has been emerged as the successor of Sesame. Would it be possible to migrate the existing code to RDF4J and to create a new release (e.g. 2.0)?

We would be very happy to contribute this using the pull request mechanism. Could you please let us know about the procedure?

**Comment by aschwarte10** [comment]
@sloesel I saw that you were active on this project quite recently. Is it possible to get in direct contact to discuss this request?

**Comment by sloesel** [comment]
Hi @aschwarte10 and thanks for you interest in db2triples. Regarding your request, it is possible to do as you suggest. The most efficient way to do this would imply that you create a topic branch (named RDF4J for example), and start the migration work. 

Once we are convinced that the new implementation is functional I could merge the branch into master and create a new release.

Would this be ok for you ?

**Comment by aschwarte10** [comment]
@sloesel Creating a separate topic branch for this sounds good. Is it possible to tweak the permissions that I can do this on your project directly, or should I create a fork and do a pull request.

Second question: do you require some kind of contributor agreement (especially since the changes have been created as part of my work). Note: I got explicit confirmation from my employer to contribute the changes back.

**Comment by sloesel** [comment]
@aschwarte10  I've given you Write permission, please tell me if this is convenient for you

We do not need any contributor agreement on our side as long as the LICENCE part is unchanged.

**Comment by aschwarte10** [comment]
@sloesel Perfect. I will prepare the change locally and will upload it to a separate feature branch, probably by beginning of next week. Note that I will also create a few issues and changes for smaller fixes and improvements that we have collected over time and add them to the same branch

**Comment by sloesel** [comment]
@aschwarte10 this is great - thanks :-)

**Comment by aschwarte10** [comment]
@sloesel @hmerat This issue is now basically resolved in master as the pull request has been merged.

How do you want to attach metadata like milestone or version to this issue?

Also: what do you think about publishing a new release of db2triples which includes these changes? In this case I would suggest to use version 2.0 (due to semantic versioning). Would it be possible to trigger the release process, say in the next month, such that we can use the official binaries?

**Comment by hmerat** [comment]
db2triples 2.0 is released and published to maven repo
I created the 2.0 milestone and used it in the 5 issues fixed by this pull request

**Comment by sloesel** [comment]
Thanks @hmerat 
@aschwarte10 thanks again for your contribution - is everything ok for you ?

**Comment by aschwarte10** [comment]
@sloesel @hmerat Thanks a lot also from my side. This was a very positive example for open source and collaboration. Everything went very smoothly
