### ISSUE TITLE
Errors while executing example code

### ISSUE THREAD

**Issue by d3cebal** [antidot/db2triples#28]
Hi I'm getting the following error when I try and execute the line as you described in the readme. This is the error:
```
Error: Could not find or load main class target.dependency.commons-codec-1.10.jar
Caused by: java.lang.ClassNotFoundException: target.dependency.commons-codec-1.10.jar
-bash: target/db2triples-2.3-SNAPSHOT.jar: Permission denied
```
I cloned the repository, opened the terminal and executed:
`mvn package`
then
`mvn dependency:copy-dependencies`

Executing `java -cp target/dependency/*:target/db2triples-<version number>.jar net.antidot.semantic.rdf.rdb2rdf.main.Db2triples` prints the expected output in terminal.

Now when I try to execute `java -cp target/dependency/*;target/db2triples-1.0.3-SNAPSHOT.jar net.antidot.semantic.rdf.rdb2rdf.main.Db2triples -m r2rml -r C:/r2rml-file.ttl -d oracle.jdbc.driver.OracleDriver -l jdbc:oracle:thin:@//some.url.and.its:port/ -u USERNAME -p PASSWORD -b database_name` with the correct database infos and r2rml file I get the errors above.

The in the target.dependency directory the commons-codec-1.10.jar exists.

What's wrong?

Greetings,
D3cebal

**Comment by hmerat** [comment]
Hi. The issue seems to be the classpath separator. In the first command you used ':' and in the second you used ';' which is for Windows.
