### ISSUE TITLE
disable DEBUG logging

### ISSUE THREAD

**Issue by VladimirAlexiev** [antidot/db2triples#29]
As built, the tool logs many hundreds of DEBUG lines per input row, which slows it down immensely.

This is due to the two files in https://github.com/antidot/db2triples/tree/master/src/main/resources.
- Edit `/commons-logging.properties` to comment out SimpleLog and use NoOpLog:
```
  org.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
  #org.apache.commons.logging.Log=org.apache.commons.logging.impl.SimpleLog
```
- Alternatively, edit `simplelog.properties` and set level INFO:
```
org.apache.commons.logging.simplelog.defaultlog=info
```

One can also fix this by directly editing those files in `target/db2triples-2.3-SNAPSHOT.jar`.

**Comment by psass-antidot** [comment]
Hello @VladimirAlexiev, thank you for creating this issue. This seems like a reasonable change. We'll gladly merge it if you provide a merge request for it.
