### ISSUE TITLE
What is the status of the project ?

### ISSUE THREAD

**Issue by Maatary** [antidot/db2triples#8]
Can it be use programatically ?

**Comment by akuckartz** [comment]
:+1: for the question

**Comment by aschwarte10** [comment]
@Maatary @akuckartz As you may have noticed, there is a new 2.0 release of db2triples out. So activity on the project depends on contributions :)

**Comment by psass-antidot** [comment]
We're not using the project internally anymore but we're merging changes if they make sense and re-release the merged code.
